// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messageStructure.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	messageStructure.proto
	subStructure.proto

It has these top-level messages:
	OutMessage
	WebSocketRequestMessage
	WebSocketResponseMessage
	WebSocketMessage
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OutMessage_Type int32

const (
	OutMessage_UNKNOWN       OutMessage_Type = 0
	OutMessage_CIPHERTEXT    OutMessage_Type = 1
	OutMessage_KEY_EXCHANGE  OutMessage_Type = 2
	OutMessage_PREKEY_BUNDLE OutMessage_Type = 3
	OutMessage_RECEIPT       OutMessage_Type = 5
)

var OutMessage_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CIPHERTEXT",
	2: "KEY_EXCHANGE",
	3: "PREKEY_BUNDLE",
	5: "RECEIPT",
}
var OutMessage_Type_value = map[string]int32{
	"UNKNOWN":       0,
	"CIPHERTEXT":    1,
	"KEY_EXCHANGE":  2,
	"PREKEY_BUNDLE": 3,
	"RECEIPT":       5,
}

func (x OutMessage_Type) Enum() *OutMessage_Type {
	p := new(OutMessage_Type)
	*p = x
	return p
}
func (x OutMessage_Type) String() string {
	return proto.EnumName(OutMessage_Type_name, int32(x))
}
func (x *OutMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutMessage_Type_value, data, "OutMessage_Type")
	if err != nil {
		return err
	}
	*x = OutMessage_Type(value)
	return nil
}
func (OutMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type OutMessage struct {
	Type             *OutMessage_Type `protobuf:"varint,1,opt,name=type,enum=models.OutMessage_Type,def=1" json:"type,omitempty"`
	Source           *string          `protobuf:"bytes,2,opt,name=source,def=" json:"source,omitempty"`
	Relay            *string          `protobuf:"bytes,3,opt,name=relay,def=" json:"relay,omitempty"`
	Timestamp        *int64           `protobuf:"varint,5,opt,name=timestamp,def=0" json:"timestamp,omitempty"`
	LegacyMessage    []byte           `protobuf:"bytes,6,opt,name=legacyMessage,def=" json:"legacyMessage,omitempty"`
	SourceDevice     *int64           `protobuf:"varint,7,opt,name=sourceDevice,def=1" json:"sourceDevice,omitempty"`
	Content          []byte           `protobuf:"bytes,8,opt,name=content,def=" json:"content,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *OutMessage) Reset()                    { *m = OutMessage{} }
func (m *OutMessage) String() string            { return proto.CompactTextString(m) }
func (*OutMessage) ProtoMessage()               {}
func (*OutMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_OutMessage_Type OutMessage_Type = OutMessage_CIPHERTEXT
const Default_OutMessage_Timestamp int64 = 0
const Default_OutMessage_SourceDevice int64 = 1

func (m *OutMessage) GetType() OutMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_OutMessage_Type
}

func (m *OutMessage) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *OutMessage) GetRelay() string {
	if m != nil && m.Relay != nil {
		return *m.Relay
	}
	return ""
}

func (m *OutMessage) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return Default_OutMessage_Timestamp
}

func (m *OutMessage) GetLegacyMessage() []byte {
	if m != nil {
		return m.LegacyMessage
	}
	return nil
}

func (m *OutMessage) GetSourceDevice() int64 {
	if m != nil && m.SourceDevice != nil {
		return *m.SourceDevice
	}
	return Default_OutMessage_SourceDevice
}

func (m *OutMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*OutMessage)(nil), "models.OutMessage")
	proto.RegisterEnum("models.OutMessage_Type", OutMessage_Type_name, OutMessage_Type_value)
}

func init() { proto.RegisterFile("messageStructure.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0xfd, 0x6b, 0xc7, 0xb6, 0xac, 0x73, 0xa8, 0x8b, 0x17, 0x43, 0x41, 0xc9, 0x29,
	0xa8, 0x17, 0x21, 0x37, 0x6d, 0x17, 0x5b, 0xaa, 0x69, 0x59, 0x13, 0xac, 0x27, 0x09, 0x71, 0x28,
	0x85, 0xa4, 0x09, 0xc9, 0x46, 0xc8, 0x57, 0xf5, 0xd3, 0x48, 0x4c, 0xa4, 0xf6, 0xf8, 0x7e, 0xf3,
	0xe6, 0x3d, 0x1e, 0x8c, 0x23, 0xca, 0x32, 0x7f, 0x4b, 0xaf, 0x3a, 0xcd, 0x03, 0x9d, 0xa7, 0x64,
	0x25, 0x69, 0xac, 0x63, 0xec, 0x46, 0xf1, 0x27, 0x85, 0xd9, 0xe4, 0xbb, 0x09, 0xb0, 0xca, 0xf5,
	0x4b, 0xe5, 0xc2, 0x7b, 0x68, 0xeb, 0x22, 0x21, 0xc1, 0x0c, 0x66, 0x8e, 0xee, 0xce, 0xad, 0xca,
	0x65, 0x1d, 0x1c, 0x96, 0x5b, 0x24, 0x64, 0xc3, 0x74, 0xb1, 0x9e, 0x4b, 0xe5, 0xca, 0x8d, 0xab,
	0x7e, 0x1f, 0x50, 0x40, 0x37, 0x8b, 0xf3, 0x34, 0x20, 0xd1, 0x34, 0x98, 0xd9, 0xb7, 0x1b, 0xaa,
	0xd6, 0x38, 0x86, 0x4e, 0x4a, 0xa1, 0x5f, 0x88, 0x56, 0x7d, 0xa8, 0x24, 0x5e, 0x42, 0x5f, 0xef,
	0x22, 0xca, 0xb4, 0x1f, 0x25, 0xa2, 0x63, 0x30, 0xb3, 0x65, 0xb3, 0x1b, 0x75, 0x60, 0x78, 0x0d,
	0xc3, 0x90, 0xb6, 0x7e, 0x50, 0xd4, 0xd5, 0xa2, 0x6b, 0x30, 0x73, 0x60, 0x37, 0xd4, 0x31, 0xc6,
	0x2b, 0x18, 0x54, 0x55, 0x33, 0xfa, 0xda, 0x05, 0x24, 0x7a, 0x55, 0xd6, 0xad, 0x3a, 0xc2, 0x78,
	0x01, 0xbd, 0x20, 0xde, 0x6b, 0xda, 0x6b, 0x71, 0x52, 0x07, 0xfd, 0x81, 0x89, 0x07, 0xed, 0x72,
	0x17, 0x9e, 0x42, 0xcf, 0x73, 0x96, 0xce, 0xea, 0xcd, 0xe1, 0x0d, 0x1c, 0xc1, 0xbf, 0x99, 0x9c,
	0x21, 0x87, 0xc1, 0x52, 0xbe, 0x7f, 0xc8, 0xcd, 0x74, 0xfe, 0xe0, 0x3c, 0x49, 0xde, 0xc4, 0x33,
	0x18, 0xae, 0x95, 0x2c, 0xe1, 0xa3, 0xe7, 0xcc, 0x9e, 0x25, 0x6f, 0x95, 0x09, 0x4a, 0x4e, 0xe5,
	0x62, 0xed, 0xf2, 0xce, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x5c, 0x40, 0x7a, 0x7d, 0x01,
	0x00, 0x00,
}
