// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subStructure.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WebSocketMessage_Type int32

const (
	WebSocketMessage_UNKNOWN  WebSocketMessage_Type = 0
	WebSocketMessage_REQUEST  WebSocketMessage_Type = 1
	WebSocketMessage_RESPONSE WebSocketMessage_Type = 2
)

var WebSocketMessage_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "REQUEST",
	2: "RESPONSE",
}
var WebSocketMessage_Type_value = map[string]int32{
	"UNKNOWN":  0,
	"REQUEST":  1,
	"RESPONSE": 2,
}

func (x WebSocketMessage_Type) Enum() *WebSocketMessage_Type {
	p := new(WebSocketMessage_Type)
	*p = x
	return p
}
func (x WebSocketMessage_Type) String() string {
	return proto.EnumName(WebSocketMessage_Type_name, int32(x))
}
func (x *WebSocketMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WebSocketMessage_Type_value, data, "WebSocketMessage_Type")
	if err != nil {
		return err
	}
	*x = WebSocketMessage_Type(value)
	return nil
}
func (WebSocketMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type WebSocketRequestMessage struct {
	Verb             *string  `protobuf:"bytes,1,opt,name=verb" json:"verb,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Headers          []string `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty"`
	Body             []byte   `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Id               *uint64  `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *WebSocketRequestMessage) Reset()                    { *m = WebSocketRequestMessage{} }
func (m *WebSocketRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*WebSocketRequestMessage) ProtoMessage()               {}
func (*WebSocketRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *WebSocketRequestMessage) GetVerb() string {
	if m != nil && m.Verb != nil {
		return *m.Verb
	}
	return ""
}

func (m *WebSocketRequestMessage) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *WebSocketRequestMessage) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WebSocketRequestMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *WebSocketRequestMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type WebSocketResponseMessage struct {
	Id               *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Status           *uint32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Message          *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Headers          []string `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty"`
	Body             []byte   `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *WebSocketResponseMessage) Reset()                    { *m = WebSocketResponseMessage{} }
func (m *WebSocketResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*WebSocketResponseMessage) ProtoMessage()               {}
func (*WebSocketResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *WebSocketResponseMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WebSocketResponseMessage) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *WebSocketResponseMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *WebSocketResponseMessage) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WebSocketResponseMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type WebSocketMessage struct {
	Type             *WebSocketMessage_Type    `protobuf:"varint,1,opt,name=type,enum=models.WebSocketMessage_Type" json:"type,omitempty"`
	Request          *WebSocketRequestMessage  `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Response         *WebSocketResponseMessage `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *WebSocketMessage) Reset()                    { *m = WebSocketMessage{} }
func (m *WebSocketMessage) String() string            { return proto.CompactTextString(m) }
func (*WebSocketMessage) ProtoMessage()               {}
func (*WebSocketMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *WebSocketMessage) GetType() WebSocketMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return WebSocketMessage_UNKNOWN
}

func (m *WebSocketMessage) GetRequest() *WebSocketRequestMessage {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *WebSocketMessage) GetResponse() *WebSocketResponseMessage {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*WebSocketRequestMessage)(nil), "models.WebSocketRequestMessage")
	proto.RegisterType((*WebSocketResponseMessage)(nil), "models.WebSocketResponseMessage")
	proto.RegisterType((*WebSocketMessage)(nil), "models.WebSocketMessage")
	proto.RegisterEnum("models.WebSocketMessage_Type", WebSocketMessage_Type_name, WebSocketMessage_Type_value)
}

func init() { proto.RegisterFile("subStructure.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0x71, 0x1a, 0xfa, 0xe7, 0xb5, 0x54, 0x91, 0x07, 0xf0, 0x82, 0x88, 0x32, 0x65, 0x8a,
	0x44, 0x37, 0x24, 0xd6, 0x4c, 0x88, 0x14, 0x5e, 0x5a, 0x75, 0x4e, 0x9a, 0x27, 0x5a, 0x41, 0x49,
	0xb0, 0x1d, 0xa4, 0x4e, 0xec, 0x7c, 0x58, 0x3e, 0x03, 0x8a, 0x53, 0x17, 0x0a, 0x0c, 0x6c, 0x77,
	0x4f, 0x77, 0xf2, 0xcf, 0x07, 0x5c, 0xd5, 0x79, 0xaa, 0x65, 0xbd, 0xd4, 0xb5, 0xa4, 0xa8, 0x92,
	0xa5, 0x2e, 0x79, 0x77, 0x53, 0x16, 0xf4, 0xa4, 0x82, 0x37, 0x38, 0x5b, 0x50, 0x9e, 0x96, 0xcb,
	0x47, 0xd2, 0x48, 0x2f, 0x35, 0x29, 0x7d, 0x4b, 0x4a, 0x65, 0x0f, 0xc4, 0x39, 0xb8, 0xaf, 0x24,
	0x73, 0xc1, 0x7c, 0x16, 0x0e, 0xd0, 0xe8, 0xe6, 0x56, 0x65, 0x7a, 0x25, 0x9c, 0xf6, 0xd6, 0x68,
	0x2e, 0xa0, 0xb7, 0xa2, 0xac, 0x20, 0xa9, 0xc4, 0xb1, 0xdf, 0x09, 0x07, 0x68, 0x6d, 0x93, 0xce,
	0xcb, 0x62, 0x2b, 0x3a, 0x3e, 0x0b, 0x47, 0x68, 0x34, 0x1f, 0x83, 0xb3, 0x2e, 0x84, 0xeb, 0xb3,
	0xd0, 0x45, 0x67, 0x5d, 0x04, 0xef, 0x0c, 0xc4, 0x37, 0x02, 0x55, 0x95, 0xcf, 0x8a, 0x2c, 0x42,
	0x1b, 0x66, 0x36, 0xcc, 0x4f, 0xa1, 0xab, 0x74, 0xa6, 0x6b, 0x65, 0x00, 0x4e, 0x70, 0xe7, 0x1a,
	0x84, 0x4d, 0x5b, 0x31, 0x6f, 0x0d, 0xd0, 0xda, 0x7f, 0xc0, 0xb9, 0x5f, 0x70, 0xc1, 0x07, 0x03,
	0x6f, 0x0f, 0x63, 0x21, 0x2e, 0xc1, 0xd5, 0xdb, 0x8a, 0x0c, 0xc6, 0x78, 0x72, 0x1e, 0xb5, 0xcb,
	0x45, 0x3f, 0x73, 0xd1, 0x6c, 0x5b, 0x11, 0x9a, 0x28, 0xbf, 0x82, 0x9e, 0x6c, 0xc7, 0x34, 0xa0,
	0xc3, 0xc9, 0xc5, 0xaf, 0xd6, 0xe1, 0xd8, 0x68, 0xf3, 0xfc, 0x1a, 0xfa, 0x72, 0xb7, 0x82, 0xf9,
	0xcb, 0x70, 0xe2, 0xff, 0xd1, 0x3d, 0x98, 0x09, 0xf7, 0x8d, 0x20, 0x02, 0xb7, 0xc1, 0xe0, 0x43,
	0xe8, 0xcd, 0x93, 0x9b, 0x64, 0xba, 0x48, 0xbc, 0xa3, 0xc6, 0x60, 0x7c, 0x3f, 0x8f, 0xd3, 0x99,
	0xc7, 0xf8, 0x08, 0xfa, 0x18, 0xa7, 0x77, 0xd3, 0x24, 0x8d, 0x3d, 0xe7, 0x33, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0x40, 0xe6, 0xc1, 0x1b, 0x02, 0x00, 0x00,
}
